//
// Generated file, do not edit! Created by nedtool 4.6 from src/message/btmessage.msg.
//

#ifndef _BTMESSAGE_M_H_
#define _BTMESSAGE_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>src/message/btmessage.msg:16</tt> by nedtool.
 * <pre>
 * //
 * // This program is free software: you can redistribute it and/or modify
 * // it under the terms of the GNU Lesser General Public License as published by
 * // the Free Software Foundation, either version 3 of the License, or
 * // (at your option) any later version.
 * // 
 * // This program is distributed in the hope that it will be useful,
 * // but WITHOUT ANY WARRANTY; without even the implied warranty of
 * // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * // GNU Lesser General Public License for more details.
 * // 
 * // You should have received a copy of the GNU Lesser General Public License
 * // along with this program.  If not, see http://www.gnu.org/licenses/.
 * //
 * message BTMessage
 * {
 *     int source;
 *     int destination;
 *     int opcode;
 *     char tag[];
 *     char pdu[];
 * }
 * </pre>
 */
class BTMessage : public ::cMessage
{
  protected:
    int source_var;
    int destination_var;
    int opcode_var;
    char *tag_var; // array ptr
    unsigned int tag_arraysize;
    char *pdu_var; // array ptr
    unsigned int pdu_arraysize;

  private:
    void copy(const BTMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const BTMessage&);

  public:
    BTMessage(const char *name=NULL, int kind=0);
    BTMessage(const BTMessage& other);
    virtual ~BTMessage();
    BTMessage& operator=(const BTMessage& other);
    virtual BTMessage *dup() const {return new BTMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSource() const;
    virtual void setSource(int source);
    virtual int getDestination() const;
    virtual void setDestination(int destination);
    virtual int getOpcode() const;
    virtual void setOpcode(int opcode);
    virtual void setTagArraySize(unsigned int size);
    virtual unsigned int getTagArraySize() const;
    virtual char getTag(unsigned int k) const;
    virtual void setTag(unsigned int k, char tag);
    virtual void setPduArraySize(unsigned int size);
    virtual unsigned int getPduArraySize() const;
    virtual char getPdu(unsigned int k) const;
    virtual void setPdu(unsigned int k, char pdu);
};

inline void doPacking(cCommBuffer *b, BTMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, BTMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef _BTMESSAGE_M_H_

